/* eslint-disable */
// Suite : sofa (la plus grosse ; doublons #content dédupliqués par external_id au parse).

export const RAW3: Record<string, string> = {
  sofa: String.raw`
https://www.ikea.com/fr/fr/p/friheten-canape-convertible-angle-rangement-skiftebo-gris-fonce-s39216754/
https://www.ikea.com/fr/fr/p/friheten-canape-convertible-angle-rangement-faringe-gris-clair-s29517045/
https://www.ikea.com/fr/fr/p/friheten-canape-convertible-angle-rangement-faringe-brun-orange-s19517041/
https://www.ikea.com/fr/fr/p/friheten-canape-convertible-angle-rangement-bomstad-noir-s69216818/
https://www.ikea.com/fr/fr/p/lycksele-loevas-canape-2-places-convertible-ransta-naturel-s99387007/
https://www.ikea.com/fr/fr/p/lycksele-loevas-canape-2-places-convertible-vansbro-jaune-s49563201/
https://www.ikea.com/fr/fr/p/friheten-convertible-3-places-bomstad-noir-20341135/
https://www.ikea.com/fr/fr/p/friheten-canape-3-places-convertible-faringe-brun-orange-90551224/
https://www.ikea.com/fr/fr/p/friheten-canape-3-places-convertible-faringe-gris-clair-60551225/
https://www.ikea.com/fr/fr/p/grunnarp-canape-3-places-convertible-gunnared-beige-30583384/
https://www.ikea.com/fr/fr/p/grunnarp-canape-3-places-convertible-gunnared-brun-rose-clair-50583397/
https://www.ikea.com/fr/fr/p/skoenabaeck-canape-2-places-convertible-knisa-gris-fonce-70582542/
https://www.ikea.com/fr/fr/p/skoenabaeck-canape-2-places-convertible-vissle-jaune-vert-60582547/
https://www.ikea.com/fr/fr/p/barsloev-convertible-3-places-meridienne-tibbleby-beige-gris-80541594/
https://www.ikea.com/fr/fr/p/barsloev-convertible-3-places-meridienne-tibbleby-gris-clair-turquoise-80530816/
https://www.ikea.com/fr/fr/p/fridhult-convertible-skiftebo-jaune-00575446/
https://www.ikea.com/fr/fr/p/tornsborg-canape-2-places-convertible-naggen-beige-pin-90584658/
https://www.ikea.com/fr/fr/p/aelvdalen-canape-3-places-convertible-knisa-gris-fonce-80462596/
https://www.ikea.com/fr/fr/p/aelvdalen-canape-3-places-convertible-knisa-gris-beige-50530648/
https://www.ikea.com/fr/fr/p/saltsjoebaden-canape-2-places-convertible-vittangi-beige-clair-blanc-s59621432/
https://www.ikea.com/fr/fr/p/saltsjoebaden-canape-2-places-convertible-blekinge-blanc-s59578589/
https://www.ikea.com/fr/fr/p/saltsjoebaden-canape-2-places-convertible-gunnared-beige-s79602729/
https://www.ikea.com/fr/fr/p/saltsjoebaden-canape-2-places-convertible-gunnared-vert-clair-s29602741/
https://www.ikea.com/fr/fr/p/vretstorp-canape-3-places-convertible-kilanda-beige-clair-s79491236/
https://www.ikea.com/fr/fr/p/vretstorp-canape-3-places-convertible-kilanda-bleu-fonce-s59491242/
https://www.ikea.com/fr/fr/p/vretstorp-canape-3-places-convertible-hakebo-gris-vert-s09491254/
https://www.ikea.com/fr/fr/p/vretstorp-canape-3-places-convertible-karlshov-gris-beige-s09491230/
https://www.ikea.com/fr/fr/p/vretstorp-canape-3-places-convertible-hakebo-gris-fonce-s29491248/
https://www.ikea.com/fr/fr/p/friheten-klagshamn-canape-convertible-angle-rangement-skiftebo-gris-fonce-s69444330/
https://www.ikea.com/fr/fr/p/friheten-klagshamn-canape-convertible-angle-rangement-faringe-brun-orange-s29520241/
https://www.ikea.com/fr/fr/p/danhult-canape-3-places-convertible-kelinge-gris-turquoise-20572461/
https://www.ikea.com/fr/fr/p/danhult-canape-3-places-convertible-silkeryd-rouille-70629950/
https://www.ikea.com/fr/fr/p/graelviken-canape-3-places-convertible-gris-fonce-40445392/
https://www.ikea.com/fr/fr/p/lindakra-canape-2-places-convertible-vissle-gris-vert-clair-20629269/
https://www.ikea.com/fr/fr/p/lindakra-canape-2-places-convertible-vissle-gris-fonce-20582610/
https://www.ikea.com/fr/fr/p/soederhamn-canape-3-places-convertible-fridtuna-bleu-gris-fonce-s59621390/
https://www.ikea.com/fr/fr/p/hyltarp-canape-2-places-convertible-gransel-naturel-s29489603/
https://www.ikea.com/fr/fr/p/holmsund-canape-convertible-dangle-kilanda-bleu-fonce-s49511293/
https://www.ikea.com/fr/fr/p/vimle-convertible-3-places-meridienne-gunnared-gris-moyen-s79545282/
https://www.ikea.com/fr/fr/p/landskrona-canape-3-places-convertible-gunnared-gris-fonce-metal-s09491273/
https://www.ikea.com/fr/fr/p/landskrona-canape-3-places-convertible-gunnared-vert-clair-metal-s39491281/
https://www.ikea.com/fr/fr/p/ikea-ps-2026-canape-3-places-convertible-skiftebo-beige-gris-clair-20620344/
https://www.ikea.com/fr/fr/p/soederhamn-convertible-4-places-avec-meridienne-viarp-beige-brun-s29616446/
https://www.ikea.com/fr/fr/p/soederhamn-convertible-4-places-avec-meridienne-gunnared-beige-s29621382/
https://www.ikea.com/fr/fr/p/vimle-can-conv-dangle-5p-meridienne-av-accoudoirs-larges-gunnared-beige-s39545203/
https://www.ikea.com/fr/fr/p/vimle-can-conv-dangle-5p-meridienne-av-accoudoirs-larges-djuparp-vert-fonce-s89537248/
https://www.ikea.com/fr/fr/p/vimle-can-conv-dangle-5p-meridienne-av-accoudoirs-larges-djuparp-vert-bleu-fonce-s79537244/
https://www.ikea.com/fr/fr/p/vimle-can-conv-dangle-5p-meridienne-av-accoudoirs-larges-gunnared-gris-moyen-s69545249/
https://www.ikea.com/fr/fr/p/vimle-can-conv-dangle-5p-meridienne-av-accoudoirs-larges-lejde-rouge-brun-s39537547/
https://www.ikea.com/fr/fr/p/vimle-can-conv-dangle-5p-meridienne-av-accoudoirs-larges-hillared-beige-s29536973/
https://www.ikea.com/fr/fr/p/vimle-can-conv-dangle-5p-meridienne-av-accoudoirs-larges-djuparp-gris-fonce-s09537247/
https://www.ikea.com/fr/fr/p/lycksele-loevas-chauffeuse-convertible-vansbro-jaune-s49563197/
https://www.ikea.com/fr/fr/p/landskrona-canape-3-places-convertible-grann-bomstad-brun-dore-bois-s09491268/
https://www.ikea.com/fr/fr/p/soederhamn-canape-3-places-kelinge-bleu-fonce-s49621630/
https://www.ikea.com/fr/fr/p/soederhamn-canape-3-places-alhamn-rouge-orange-fonce-s99621642/
https://www.ikea.com/fr/fr/p/soederhamn-canape-3-places-fridtuna-bleu-gris-fonce-s19621636/
https://www.ikea.com/fr/fr/p/soederhamn-canape-3-places-kelinge-beige-s89621633/
https://www.ikea.com/fr/fr/p/soederhamn-canape-3-places-kelinge-jaune-fonce-s09621627/
https://www.ikea.com/fr/fr/p/soederhamn-canape-3-places-viarp-beige-brun-s69305697/
https://www.ikea.com/fr/fr/p/soederhamn-canape-3-places-knaebaeck-anthracite-s99607165/
https://www.ikea.com/fr/fr/p/soederhamn-canape-3-places-tallmyra-blanc-noir-s99430652/
https://www.ikea.com/fr/fr/p/lillesaeter-canape-3-places-axvall-blanc-casse-40619071/
https://www.ikea.com/fr/fr/p/lillesaeter-canape-3-places-gunnared-jaune-vert-vif-30618492/
https://www.ikea.com/fr/fr/p/glostad-canape-3-places-knisa-gris-fonce-40573285/
https://www.ikea.com/fr/fr/p/soederhamn-canape-4-places-meridienne-et-sans-accoudoir-kelinge-jaune-fonce-s99621680/
https://www.ikea.com/fr/fr/p/soederhamn-canape-4-places-meridienne-et-sans-accoudoir-johanneshov-vert-fonce-s69621667/
https://www.ikea.com/fr/fr/p/soederhamn-canape-4-places-meridienne-et-sans-accoudoir-kelinge-beige-s29621674/
https://www.ikea.com/fr/fr/p/soederhamn-canape-4-places-meridienne-et-sans-accoudoir-johanneshov-blanc-casse-s29621669/
https://www.ikea.com/fr/fr/p/soederhamn-canape-4-places-meridienne-et-sans-accoudoir-johanneshov-brun-beige-s59621781/
https://www.ikea.com/fr/fr/p/soederhamn-canape-4-places-meridienne-et-sans-accoudoir-johanneshov-gris-fonce-s09621665/
https://www.ikea.com/fr/fr/p/soederhamn-canape-4-places-meridienne-sans-accoudoir-tallmyra-vert-fonce-s79580336/
https://www.ikea.com/fr/fr/p/soederhamn-canape-4-places-meridienne-et-sans-accoudoir-alhamn-bleu-gris-fonce-s99621784/
https://www.ikea.com/fr/fr/p/soederhamn-canape-4-places-meridienne-et-sans-accoudoir-knaebaeck-anthracite-s59607172/
https://www.ikea.com/fr/fr/p/ektorp-canape-3-places-hakebo-gris-fonce-s39508998/
https://www.ikea.com/fr/fr/p/ektorp-canape-3-places-hakebo-gris-vert-s59509001/
https://www.ikea.com/fr/fr/p/ektorp-canape-3-places-kilanda-beige-clair-s69509010/
https://www.ikea.com/fr/fr/p/ektorp-canape-3-places-kilanda-bleu-fonce-s29509007/
https://www.ikea.com/fr/fr/p/ektorp-canape-3-places-hillared-anthracite-s79430530/
https://www.ikea.com/fr/fr/p/ektorp-canape-3-places-tallmyra-bleu-s49430536/
https://www.ikea.com/fr/fr/p/ektorp-canape-3-places-tallmyra-vert-clair-s09430538/
https://www.ikea.com/fr/fr/p/ektorp-canape-3-places-tallmyra-vert-fonce-s29430537/
https://www.ikea.com/fr/fr/p/soederhamn-module-3-places-tonerud-gris-s39452053/
https://www.ikea.com/fr/fr/p/soederhamn-module-3-places-gunnared-beige-s39305415/
https://www.ikea.com/fr/fr/p/soederhamn-module-3-places-fridtuna-bleu-gris-fonce-s59621597/
https://www.ikea.com/fr/fr/p/soederhamn-module-3-places-kelinge-bleu-fonce-s19621603/
https://www.ikea.com/fr/fr/p/soederhamn-module-3-places-kelinge-jaune-fonce-s79621600/
https://www.ikea.com/fr/fr/p/soederhamn-module-3-places-knaebaeck-anthracite-s29607116/
https://www.ikea.com/fr/fr/p/soederhamn-module-3-places-tallmyra-vert-fonce-s29430603/
https://www.ikea.com/fr/fr/p/soederhamn-module-3-places-johanneshov-vert-fonce-s49621611/
https://www.ikea.com/fr/fr/p/stockholm-2025-canape-3-places-djurmo-gris-blanc-s59574303/
https://www.ikea.com/fr/fr/p/stockholm-2025-canape-3-places-alhamn-brun-fonce-s39574295/
https://www.ikea.com/fr/fr/p/stockholm-2025-canape-3-places-alhamn-beige-s09574292/
https://www.ikea.com/fr/fr/p/stockholm-2025-canape-3-places-alhamn-turquoise-fonce-s19574300/
https://www.ikea.com/fr/fr/p/gullvalla-canape-2-places-silkeryd-beige-gris-fonce-30618500/
https://www.ikea.com/fr/fr/p/gullvalla-canape-2-places-silkeryd-gris-vert-70613398/
https://www.ikea.com/fr/fr/p/jaettebo-canape-modulable-4places-meridienne-droite-samsala-vert-jaune-fonce-s59485199/
https://www.ikea.com/fr/fr/p/jaettebo-canape-modulable-4places-meridienne-droite-tonerud-gris-s89485211/
https://www.ikea.com/fr/fr/p/jaettebo-canape-modulable-4places-meridienne-droite-samsala-bleu-fonce-s29608347/
https://www.ikea.com/fr/fr/p/jaettebo-canape-modulable-4places-meridienne-droite-samsala-gris-beige-s09485205/
https://www.ikea.com/fr/fr/p/jaettebo-canape-modulable-4places-meridienne-droite-samsala-brun-jaune-s89608349/
https://www.ikea.com/fr/fr/p/jaettebo-canape-modulable-4places-meridienne-droite-samsala-rouille-s69608350/
https://www.ikea.com/fr/fr/p/jaettebo-canape-modulable-4places-meridienne-droite-axvall-bleu-gris-fonce-s59608398/
https://www.ikea.com/fr/fr/p/jaettebo-canape-modulable-4places-meridienne-droite-johanneshov-vert-fonce-s99608400/
https://www.ikea.com/fr/fr/p/landskrona-canape-3-places-grann-bomstad-noir-bois-s59031702/
https://www.ikea.com/fr/fr/p/stockholm-2025-canape-2-places-djurmo-gris-blanc-90586110/
https://www.ikea.com/fr/fr/p/stockholm-2025-canape-2-places-alhamn-beige-30586108/
https://www.ikea.com/fr/fr/p/stockholm-2025-canape-2-places-alhamn-turquoise-fonce-10586109/
https://www.ikea.com/fr/fr/p/kivik-canape-dangle-4-places-kelinge-gris-turquoise-s99443013/
https://www.ikea.com/fr/fr/p/kivik-canape-dangle-4-places-tresund-beige-clair-s89482854/
https://www.ikea.com/fr/fr/p/kivik-canape-dangle-4-places-tresund-anthracite-s09482853/
https://www.ikea.com/fr/fr/p/kivik-canape-dangle-4-places-gunnared-beige-s99484739/
https://www.ikea.com/fr/fr/p/kivik-canape-dangle-4-places-gunnared-bleu-s19484738/
https://www.ikea.com/fr/fr/p/kivik-canape-dangle-4-places-tallmyra-beige-s09484734/
https://www.ikea.com/fr/fr/p/kivik-canape-dangle-4-places-tallmyra-vert-clair-s69484731/
https://www.ikea.com/fr/fr/p/kivik-canape-dangle-4-places-tallmyra-vert-fonce-s49484732/
https://www.ikea.com/fr/fr/p/grillstorp-smedstorp-canape-2-places-gunnared-brun-rose-clair-chene-s49549955/
https://www.ikea.com/fr/fr/p/grillstorp-smedstorp-canape-2-places-gunnared-gris-fonce-chene-s69549959/
https://www.ikea.com/fr/fr/p/grillstorp-smedstorp-canape-2-places-viarp-beige-brun-chene-s19549952/
https://www.ikea.com/fr/fr/p/smedstorp-canape-2-places-viarp-beige-brun-chene-s19418606/
https://www.ikea.com/fr/fr/p/smedstorp-canape-2-places-djuparp-gris-fonce-chene-s09418598/
https://www.ikea.com/fr/fr/p/smedstorp-canape-2-places-djuparp-gris-fonce-noir-s39418605/
https://www.ikea.com/fr/fr/p/smedstorp-canape-2-places-viarp-beige-brun-noir-s19418611/
https://www.ikea.com/fr/fr/p/soederhamn-canape-dangle-3-places-tonerud-gris-s19452068/
https://www.ikea.com/fr/fr/p/soederhamn-canape-dangle-3-places-fridtuna-beige-clair-s79449657/
https://www.ikea.com/fr/fr/p/soederhamn-canape-dangle-3-places-fridtuna-bleu-gris-fonce-s69622172/
https://www.ikea.com/fr/fr/p/soederhamn-canape-dangle-3-places-fridtuna-gris-fonce-s59449583/
https://www.ikea.com/fr/fr/p/soederhamn-canape-dangle-3-places-kelinge-bleu-fonce-s89622166/
https://www.ikea.com/fr/fr/p/soederhamn-canape-dangle-3-places-kelinge-jaune-fonce-s59622163/
https://www.ikea.com/fr/fr/p/soederhamn-canape-dangle-3-places-knaebaeck-anthracite-s49607144/
https://www.ikea.com/fr/fr/p/soederhamn-canape-dangle-3-places-gransel-naturel-s19622184/
https://www.ikea.com/fr/fr/p/vimle-canape-3-places-av-accoudoirs-larges-gunnared-beige-s69401335/
https://www.ikea.com/fr/fr/p/vimle-canape-3-places-av-accoudoirs-larges-gunnared-gris-moyen-s19401333/
https://www.ikea.com/fr/fr/p/vimle-canape-3-places-av-accoudoirs-larges-djuparp-vert-fonce-s69432681/
https://www.ikea.com/fr/fr/p/vimle-canape-3-places-av-accoudoirs-larges-hallarp-beige-s59401430/
https://www.ikea.com/fr/fr/p/vimle-canape-3-places-av-accoudoirs-larges-djuparp-vert-bleu-fonce-s89432680/
https://www.ikea.com/fr/fr/p/ektorp-canape-3-places-avec-meridienne-hakebo-gris-fonce-s89509028/
https://www.ikea.com/fr/fr/p/ektorp-canape-3-places-avec-meridienne-hillared-anthracite-s49430541/
https://www.ikea.com/fr/fr/p/ektorp-canape-3-places-avec-meridienne-hillared-beige-s29430542/
https://www.ikea.com/fr/fr/p/ektorp-canape-3-places-avec-meridienne-kilanda-bleu-fonce-s99509037/
https://www.ikea.com/fr/fr/p/ektorp-canape-3-places-avec-meridienne-tallmyra-beige-s39430546/
https://www.ikea.com/fr/fr/p/ektorp-canape-3-places-avec-meridienne-tallmyra-bleu-s19430547/
https://www.ikea.com/fr/fr/p/ektorp-canape-3-places-avec-meridienne-tallmyra-vert-fonce-s99430548/
https://www.ikea.com/fr/fr/p/jaettebo-canap-modul-4-5-pl-merid-droite-tonerud-gris-s79471403/
https://www.ikea.com/fr/fr/p/jaettebo-canap-modul-4-5-pl-merid-droite-samsala-bleu-fonce-s79607703/
https://www.ikea.com/fr/fr/p/jaettebo-canap-modul-4-5-pl-merid-droite-samsala-gris-beige-s79469481/
https://www.ikea.com/fr/fr/p/jaettebo-canap-modul-4-5-pl-merid-droite-samsala-vert-jaune-fonce-s99471402/
https://www.ikea.com/fr/fr/p/jaettebo-canap-modul-4-5-pl-merid-droite-samsala-brun-jaune-s09607706/
https://www.ikea.com/fr/fr/p/jaettebo-canap-modul-4-5-pl-merid-droite-samsala-rouille-s69607708/
https://www.ikea.com/fr/fr/p/jaettebo-canap-modul-4-5-pl-merid-droite-axvall-blanc-casse-s29607710/
https://www.ikea.com/fr/fr/p/jaettebo-canap-modul-4-5-pl-merid-droite-axvall-bleu-gris-fonce-s89607712/
https://www.ikea.com/fr/fr/p/jaettebo-canap-modul-4-5-pl-merid-droite-johanneshov-vert-fonce-s99607716/
https://www.ikea.com/fr/fr/p/landskrona-canape-2-places-gunnared-gris-fonce-bois-s49270279/
https://www.ikea.com/fr/fr/p/lillesaeter-canape-4-places-axvall-blanc-casse-s49614291/
https://www.ikea.com/fr/fr/p/lillesaeter-canape-4-places-gunnared-jaune-vert-vif-s69614271/
https://www.ikea.com/fr/fr/p/jaettebo-canape-modulaire-2-places-johanneshov-vert-fonce-s89608269/
https://www.ikea.com/fr/fr/p/jaettebo-canape-modulaire-2-places-axvall-blanc-casse-s49608266/
https://www.ikea.com/fr/fr/p/landskrona-canape-3-places-avec-meridienne-gunnared-gris-fonce-bois-s09272666/
https://www.ikea.com/fr/fr/p/viskafors-canape-3-places-lejde-anthracite-bouleau-s39443327/
https://www.ikea.com/fr/fr/p/viskafors-canape-3-places-lejde-beige-clair-brun-s99443372/
https://www.ikea.com/fr/fr/p/lillesaeter-canape-5-places-axvall-blanc-casse-s59614295/
https://www.ikea.com/fr/fr/p/viskafors-canape-2-places-hoegalid-brun-bouleau-s49443242/
`,
};
